### ISSUE TITLE
Constraints

### ISSUE THREAD

**Issue by tal32123** [dwave-examples/employee-scheduling#15]
I'm curious if this can take several constraints, such as I want the person to have x attributes and to be available for a template of shifts so on 2/22/2022, 4/22/2022, 4/25/2022, etc. or find the top x people who fits most of those.

**Comment by vgoliber** [comment]
This could easily be modified to take in more complex constraints.
- We can use the employee preferences information (currently randomly generated) to indicate availability or non-availability for certain shifts.
- We can add features to employees and add equality-type constraints that employees assigned to certain shifts must have a given feature equal to a specific value. 

The easiest way to add these more complex constraints is to use the newer CQM objects and corresponding hybrid solver. See the open PR to observe how we can map the same problem to a CQM and solve with the hybrid solver available.
